---
sidebar: sidebar 
permalink: codebox-automation.html 
keywords: codebox, automation 
summary: 'Codebox는 개발자와 DevOps가 NetApp Workload Factory에서 지원하는 모든 작업을 실행하는 데 필요한 코드를 생성하는 데 도움이 되는 Infrastructure as Code(IaC) 공동 파일럿입니다.' 
---
= 코드박스 자동화에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Codebox는 개발자와 DevOps가 NetApp Workload Factory 에서 지원하는 모든 작업을 실행하는 데 필요한 코드를 생성하는 데 도움이 되는 Infrastructure as Code(IaC) 공동 파일럿입니다.  Codebox는 Workload Factory 권한 정책에 맞춰져 있으며 실행 준비에 대한 명확한 경로를 설정하는 동시에 향후 빠른 재사용을 위한 자동화 카탈로그를 제공합니다.



== 코드박스 기능

Codebox는 두 가지 주요 IAC 기능을 제공합니다.

* _Codebox 뷰어 _ 는 그래픽 마법사 또는 대화 채팅 인터페이스에서 항목과 선택을 일치시켜 특정 작업 흐름 작업에 의해 생성되는 IAC를 표시합니다. Codebox 뷰어는 간편한 탐색 및 분석을 위해 색상 코딩을 지원하지만, 자동화 카탈로그에 코드를 복사하거나 저장하는 것은 허용되지 않습니다.
* _Codebox Automation Catalog_ 저장된 모든 IAC 작업을 표시하여 나중에 사용할 수 있도록 쉽게 참조할 수 있습니다. 자동화 카탈로그 작업은 템플릿으로 저장되고 적용되는 리소스의 컨텍스트로 표시됩니다.


또한 Workload Factory 자격 증명을 설정할 때 Codebox는 IAM 정책을 만드는 데 필요한 AWS 권한을 동적으로 표시합니다.  사용하려는 각 Workload Factory 기능(데이터베이스, AI, FSx for ONTAP 등)에 대한 권한이 제공되며 사용자 정의가 가능합니다.  Codebox에서 권한을 복사한 다음 AWS Management Console에 붙여넣으면 Workload Factory가 워크로드를 관리할 수 있는 올바른 권한을 갖게 됩니다.



== 지원되는 코드 형식

지원되는 코드 형식은 다음과 같습니다.

* 워크로드 팩토리 REST API
* AWS CLI를 참조하십시오
* AWS CloudFormation 을 참조하십시오
* 테라폼




== 관련 정보

link:use-codebox.html["Codebox 사용 방법에 대해 알아봅니다"]..

link:https://console.workloads.netapp.com/api-doc["Workload Factory REST API 문서"^] .
