---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 특정 유형의 이벤트가 발생하면 개인이나 다른 애플리케이션에 알림을 보내도록 NetApp Workload Factory를 구성할 수 있습니다. 
---
= NetApp Workload Factory 알림 구성
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 알림 서비스를 구성하여 NetApp 콘솔이나 Amazon SNS 주제에 알림을 보낼 수 있습니다.  콘솔 에이전트나 링크가 배포된 경우 경고로 전송된 알림은 NetApp 콘솔에 나타납니다.  Workload Factory가 Amazon SNS 주제에 알림을 게시하면 해당 주제의 구독자(예: 사람 또는 다른 애플리케이션)는 해당 주제에 대해 구성된 엔드포인트(예: 이메일 또는 SMS 메시지)에서 알림을 받습니다.



== 알림 유형 및 메시지

Workload Factory는 다음 이벤트에 대한 알림을 보냅니다.

[cols="6*"]
|===
| 이벤트 | 설명 | 알림 유형입니다 | 심각도입니다 | 워크로드 | 리소스 유형 


| 계정의 일부 데이터베이스 인스턴스가 제대로 설계되지 않았습니다. | 귀하 계정의 모든 Microsoft SQL Server 인스턴스는 잘 설계된 문제에 대해 분석되었습니다.  이 이벤트에 대한 설명은 잘 설계된 인스턴스와 최적화되지 않은 인스턴스의 수를 제공합니다.  Workload Factory 콘솔의 데이터베이스 인벤토리에서 잘 설계된 상태 결과와 권장 사항을 검토합니다. | 잘 설계된 | 권장 사항 | 데이터베이스를 지원합니다 | Microsoft SQL Server 인스턴스 


| Microsoft SQL Server/PostgreSQL 서버 배포가 성공했습니다. | Microsoft SQL Server 또는 PostgreSQL 호스트 배포가 성공했습니다. 자세한 내용은 작업 모니터링을 참조하세요. | 구축 | 성공 | 데이터베이스를 지원합니다 | ONTAP용 FSx, DB 호스트 


| Microsoft SQL Server/PostgreSQL 서버 배포에 실패했습니다. | Microsoft SQL Server 또는 PostgreSQL 호스트 배포에 실패했습니다. 자세한 내용은 작업 모니터링을 참조하세요. | 구축 | 오류 | 데이터베이스를 지원합니다 | ONTAP용 FSx, DB 호스트 


| 복제 관계 생성에 실패했습니다. | SnapMirror 복제 관계 생성에 실패했습니다.  자세한 내용은 Tracker를 참조하세요. | 복제 | 비판적인 | 일반 보관 | ONTAP 용 FSx 


| ONTAP 생성 실패를 위한 FSx | FSx for ONTAP 파일 시스템 생성 프로세스가 실패했습니다.  자세한 내용은 Tracker를 참조하세요. | FSx for ONTAP 파일 시스템 작업 | 비판적인 | 일반 보관 | ONTAP 용 FSx 


| FSx for ONTAP 문제가 감지되었습니다. | 모든 FSx for ONTAP 파일 시스템은 잘 설계된 문제에 대해 분석되었습니다.  검사 결과 하나 이상의 문제가 감지되었습니다.  자세한 내용은 Workload Factory 콘솔의 Storage 대시보드에서 잘 설계된 분석을 검토하세요. | 잘 설계된 분석 | 권장 사항 | 일반 보관 | ONTAP 파일 시스템용 FSx 
|===


== Workload Factory 알림 구성

NetApp 콘솔이나 Workload Factory 콘솔을 사용하여 Workload Factory 알림을 구성합니다.  NetApp 콘솔을 사용하는 경우 Workload Factory를 구성하여 NetApp 콘솔이나 Amazon SNS 주제로 알림을 보낼 수 있습니다.  NetApp 콘솔의 *알림 설정*에서 알림을 구성할 수 있습니다.

.시작하기 전에
* Amazon SNS 콘솔이나 AWS CLI를 사용하여 Amazon SNS를 구성하고 Amazon SNS 주제를 생성해야 합니다.
* Workload Factory는 *표준* 주제 유형을 지원합니다.  이 유형의 주제에서는 알림이 수신 순서대로 구독자에게 전송되지 않으므로 중요하거나 긴급한 알림이 있는 경우 이 점을 고려하세요.


[role="tabbed-block"]
====
.NetApp 콘솔에서 알림 구성
--
.단계
. 에 로그인하세요link:https://console.netapp.com["NetApp 콘솔"^] .
. NetApp 콘솔 메뉴에서 *워크로드*, *관리*, *알림 설정*을 차례로 선택합니다.
. 알림 설정 페이지에서 다음을 수행하세요.
+
.. 선택 사항: NetApp 콘솔에서 알림을 보내도록 Workload Factory를 구성하려면 * NetApp 콘솔 알림 사용*을 선택합니다.
.. *SNS 알림 사용*을 선택하세요.
.. Amazon SNS 콘솔에서 Amazon SNS를 구성하려면 지침을 따르세요.
+
주제를 만든 후 주제 ARN을 복사하여 *알림 설정* 페이지의 *SNS 주제 ARN* 필드에 입력합니다.



. 테스트 알림을 보내 구성을 확인한 후 *적용*을 선택합니다.


.결과
Workload Factory는 사용자가 지정한 Amazon SNS 주제에 알림을 보내도록 구성되었습니다.

--
.Workload Factory 콘솔에서 알림 구성
--
.단계
. 에 로그인하세요link:https://console.workloads.netapp.com["워크로드 팩토리 콘솔"^] .
. Workload Factory 콘솔 메뉴에서 *워크로드*, *관리*, *알림 설정*을 차례로 선택합니다.
. *SNS 알림 사용*을 선택하세요.
. Amazon SNS 콘솔에서 Amazon SNS를 구성하려면 지침을 따르세요.
. 테스트 알림을 보내 구성을 확인한 후 *적용*을 선택합니다.


.결과
Workload Factory는 사용자가 지정한 Amazon SNS 주제에 알림을 보내도록 구성되었습니다.

--
====


== Amazon SNS 주제 구독하기

Workload Factory를 구성하여 주제에 알림을 보낸 후 다음을 따르세요. https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["지침"] Workload Factory에서 알림을 받을 수 있도록 Amazon SNS 설명서에서 주제를 구독하세요.



== 알림을 필터링합니다

알림에 필터를 적용하면 불필요한 알림 트래픽을 줄이고 특정 사용자를 대상으로 특정 알림 유형을 타겟팅할 수 있습니다.  SNS 알림에 대한 Amazon SNS 정책을 사용하고 NetApp 콘솔의 알림 설정을 사용하여 이 작업을 수행할 수 있습니다.



=== Amazon SNS 알림 필터링

Amazon SNS 주제를 구독하면 기본적으로 해당 주제에 게시된 모든 알림을 받게 됩니다.  해당 주제의 특정 알림만 받으려면 필터 정책을 사용하여 받을 알림을 제어할 수 있습니다.  필터 정책을 사용하면 Amazon SNS가 필터 정책과 일치하는 알림만 구독자에게 전달합니다.

다음 기준으로 Amazon SNS 알림을 필터링할 수 있습니다.

[cols="3*"]
|===
| 설명 | 필터 정책 필드 이름 | 가능한 값 


| 리소스 유형 | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| 워크로드 | `workload` | `WLMDB` 


| 우선 사항 | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| 알림 유형입니다 | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.단계
. Amazon SNS 콘솔에서 SNS 주제에 대한 구독 세부 정보를 편집합니다.
. *구독 필터 정책* 영역에서 *메시지 속성*으로 필터링하도록 선택합니다.
. *구독 필터 정책* 옵션을 활성화합니다.
. *JSON 편집기* 상자에 JSON 필터 정책을 입력합니다.
+
예를 들어, 다음 JSON 필터 정책은 WLMDB 작업 부하와 관련된 Microsoft SQL Server 리소스의 알림을 수락하고, 성공 또는 오류의 우선순위를 가지며, Well-architected 상태에 대한 세부 정보를 제공합니다.

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. *변경 사항 저장*을 선택하세요.


필터 정책의 다른 예는 다음을 참조하세요. https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Amazon SNS 필터 정책 예시"^] .

필터 정책 생성에 대한 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["아마존 SNS 문서"^] .



=== NetApp 콘솔에서 알림 필터링

NetApp 콘솔 알림 설정을 사용하면 콘솔에서 받는 알림을 중요, 정보, 경고 등의 심각도 수준에 따라 필터링할 수 있습니다.

콘솔에서 알림 필터링에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["NetApp 콘솔 설명서"^] .
