---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 특정 유형의 이벤트가 발생하면 개인이나 다른 애플리케이션에 알림을 보내도록 BlueXP 워크로드 팩토리를 구성할 수 있습니다. 
---
= BlueXP 워크로드 팩토리 알림 구성
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP 워크로드 팩토리 알림 서비스를 구성하여 BlueXP 알림 서비스 또는 Amazon SNS 주제로 알림을 보낼 수 있습니다. BlueXP 알림으로 전송된 알림은 BlueXP 알림 패널에 표시됩니다. 워크로드 팩토리가 Amazon SNS 주제에 알림을 게시하면 해당 주제 구독자(예: 사용자 또는 다른 애플리케이션)는 해당 주제에 대해 구성된 엔드포인트(예: 이메일 또는 SMS 메시지)에서 알림을 수신합니다.



== 알림 유형 및 메시지

워크로드 팩토리는 다음 이벤트에 대한 알림을 보냅니다.

[cols="6*"]
|===
| 이벤트 | 설명 | 알림 유형입니다 | 심각도입니다 | 워크로드 | 리소스 유형 


| 계정의 일부 데이터베이스 인스턴스가 제대로 설계되지 않았습니다. | 계정의 모든 Microsoft SQL Server 인스턴스에서 잘 설계된(Well-Architected) 문제가 분석되었습니다. 이 이벤트에 대한 설명에는 잘 설계된 인스턴스와 최적화되지 않은 인스턴스의 수가 나와 있습니다. 워크로드 팩토리 콘솔의 데이터베이스 인벤토리에서 잘 설계된 상태 결과 및 권장 사항을 검토하세요. | 잘 설계된 | 권장 사항 | 데이터베이스를 지원합니다 | Microsoft SQL Server 인스턴스 


| Microsoft SQL Server/PostgreSQL 서버 배포가 성공했습니다. | Microsoft SQL Server 또는 PostgreSQL 호스트 배포가 성공했습니다. 자세한 내용은 작업 모니터링을 참조하세요. | 구축 | 성공 | 데이터베이스를 지원합니다 | ONTAP용 FSx, DB 호스트 


| Microsoft SQL Server/PostgreSQL 서버 배포에 실패했습니다. | Microsoft SQL Server 또는 PostgreSQL 호스트 배포에 실패했습니다. 자세한 내용은 작업 모니터링을 참조하세요. | 구축 | 오류 | 데이터베이스를 지원합니다 | ONTAP용 FSx, DB 호스트 


| 복제 관계 생성에 실패했습니다. | SnapMirror 복제 관계 생성에 실패했습니다.  자세한 내용은 Tracker를 참조하세요. | 복제 | 비판적인 | 일반 보관 | ONTAP 용 FSx 


| ONTAP 생성 실패를 위한 FSx | FSx for ONTAP 파일 시스템 생성 프로세스가 실패했습니다.  자세한 내용은 Tracker를 참조하세요. | FSx for ONTAP 파일 시스템 작업 | 비판적인 | 일반 보관 | ONTAP 용 FSx 
|===


== 작업 부하 공장 알림 구성

BlueXP 콘솔 또는 워크로드 팩토리 콘솔을 사용하여 워크로드 팩토리 알림을 구성하세요. BlueXP 콘솔을 사용하는 경우, BlueXP 알림 또는 Amazon SNS 주제로 알림을 보내도록 워크로드 팩토리를 구성할 수 있습니다. BlueXP의 *알림 및 알림 설정* 영역에서 BlueXP 알림을 구성할 수 있습니다.

.시작하기 전에
* Amazon SNS 콘솔이나 AWS CLI를 사용하여 Amazon SNS를 구성하고 Amazon SNS 주제를 생성해야 합니다.
* 워크로드 팩토리는 *표준* 토픽 유형을 지원합니다. 이 토픽 유형은 구독자에게 수신된 순서대로 알림을 전송하지 않으므로, 중요하거나 긴급한 알림이 있는 경우 이 유형을 고려하세요.


[role="tabbed-block"]
====
.BlueXP 콘솔에서 알림 구성
--
.단계
. 에 link:https://console.bluexp.netapp.com["BlueXP 콘솔"^]로그인합니다.
. 왼쪽 탐색 모음에서 * 워크로드 * 를 선택합니다.
. 모든 워크로드를 보려면 * Home * 을 선택하고 * Storage * 또는 * Databases * 와 같은 하나의 워크로드를 선택하십시오.
. 워크로드 팩토리 메뉴 표시줄에서 구성 메뉴를 선택합니다.
. 메뉴에서 *Workload Factory 알림 설정*을 선택합니다.
. 선택 사항: BlueXP 알림 활성화를 선택하여 워크로드 팩토리가 BlueXP 알림에 알림을 보내도록 구성합니다.
. *SNS 알림 사용*을 선택하세요.
. Amazon SNS 콘솔에서 Amazon SNS를 구성하려면 지침을 따르세요.
+
주제를 만든 후 주제 ARN을 복사하여 *알림 설정* 대화 상자의 *SNS 주제 ARN* 필드에 입력합니다.

. 테스트 알림을 보내 구성을 확인한 후 *적용*을 선택합니다.


.결과
워크로드 팩토리는 사용자가 지정한 Amazon SNS 주제에 알림을 보내도록 구성되었습니다.

--
.워크로드 팩토리 콘솔에서 알림 구성
--
.단계
. 에 link:https://console.workloads.netapp.com["워크로드 팩토리 콘솔"^]로그인합니다.
. 상단 탐색 표시줄에서 계정 메뉴를 엽니다.
. 메뉴에서 *알림 설정*을 선택하세요.
. *SNS 알림 사용*을 선택하세요.
. Amazon SNS 콘솔에서 Amazon SNS를 구성하려면 지침을 따르세요.
. 테스트 알림을 보내 구성을 확인한 후 *적용*을 선택합니다.


.결과
워크로드 팩토리는 사용자가 지정한 Amazon SNS 주제에 알림을 보내도록 구성되었습니다.

--
====


== Amazon SNS 주제 구독하기

주제에 알림을 보내도록 작업 부하 팩토리를 구성한 후 다음을 따르세요.  https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["지침"] Amazon SNS 설명서에서 주제를 구독하면 워크로드 팩토리에서 알림을 받을 수 있습니다.



== 알림을 필터링합니다

알림에 필터를 적용하여 불필요한 알림 트래픽을 줄이고 특정 사용자에게 특정 알림 유형을 타겟팅할 수 있습니다. SNS 알림에는 Amazon SNS 정책을, BlueXP 알림에는 BlueXP 알림 설정을 사용하면 됩니다.



=== Amazon SNS 알림 필터링

Amazon SNS 주제를 구독하면 기본적으로 해당 주제에 게시된 모든 알림을 받게 됩니다.  해당 주제의 특정 알림만 받으려면 필터 정책을 사용하여 받을 알림을 제어할 수 있습니다.  필터 정책을 사용하면 Amazon SNS가 필터 정책과 일치하는 알림만 구독자에게 전달합니다.

다음 기준으로 Amazon SNS 알림을 필터링할 수 있습니다.

[cols="3*"]
|===
| 설명 | 필터 정책 필드 이름 | 가능한 값 


| 리소스 유형 | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| 워크로드 | `workload` | `WLMDB` 


| 우선 사항 | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| 알림 유형입니다 | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.단계
. Amazon SNS 콘솔에서 SNS 주제에 대한 구독 세부 정보를 편집합니다.
. *구독 필터 정책* 영역에서 *메시지 속성*으로 필터링하도록 선택합니다.
. *구독 필터 정책* 옵션을 활성화합니다.
. *JSON 편집기* 상자에 JSON 필터 정책을 입력합니다.
+
예를 들어, 다음 JSON 필터 정책은 WLMDB 작업 부하와 관련된 Microsoft SQL Server 리소스의 알림을 수락하고, 성공 또는 오류의 우선순위를 가지며, Well-architected 상태에 대한 세부 정보를 제공합니다.

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. *변경 사항 저장*을 선택하세요.


필터 정책의 다른 예는 다음을 참조하세요. https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Amazon SNS 필터 정책 예시"^] .

필터 정책 생성에 대한 자세한 내용은 다음을 참조하세요. https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["아마존 SNS 문서"^] .



=== BlueXP 알림 필터링

BlueXP 경고 및 알림 설정을 사용하면 BlueXP에서 받는 경고 및 알림을 중요, 정보, 경고 등의 심각도 수준에 따라 필터링할 수 있습니다.

BlueXP에서 알림 필터링에 대한 자세한 내용은 다음을 참조하세요.  https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#filter-notifications["BlueXP 설명서"^] .
