---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Workload Factory 링크는 Workload Factory 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간의 신뢰 관계 및 연결을 생성합니다. 
---
= NetApp Workload Factory 링크에 대해 알아보기
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 링크는 Workload Factory 계정과 하나 이상의 FSx for ONTAP 파일 시스템 간의 신뢰 관계 및 연결을 생성합니다. 이를 통해 Amazon FSx for ONTAP API를 통해 사용할 수 없는 특정 파일 시스템 기능을 ONTAP REST API 호출을 통해 직접 모니터링하고 관리할 수 있습니다.

Workload Factory를 시작하는 데는 링크가 필요하지 않지만, 어떤 경우에는 모든 Workload Factory 기능과 워크로드 기능을 잠금 해제하려면 링크를 만들어야 합니다.



[[why-links-are-beneficial]]
== 링크가 유익한 이유

링크는 Workload Factory가 Amazon FSx for ONTAP API를 통해 기본적으로 제공되지 않는 작업을 수행할 수 있도록 해주기 때문에 유용합니다. 링크를 통해 고급 ONTAP 기능과 자동화를 활용하여 FSx for ONTAP 파일 시스템 관리를 향상시킬 수 있습니다.

링크 사용의 이점은 다음과 같습니다.

* 이 링크를 통해 NetApp Console은 ONTAP 명령을 FSx for ONTAP 파일 시스템으로 직접 전송할 수 있으므로 AWS에서 기본적으로 제공하는 기능 이상의 고급 ONTAP 기능을 활용할 수 있습니다.
* Links는 AWS Lambda를 활용하여 이벤트에 대한 응답으로 코드를 실행합니다. 이러한 서버리스 접근 방식을 통해 VPC 내에서 실행되는 인스턴스에 대한 의존성을 제거할 수 있습니다.




[[how-links-work]]
== 링크 작동 방식

링크는 AWS Lambda를 활용합니다. Lambda는 이벤트에 응답하여 코드를 실행하고 해당 코드에 필요한 컴퓨팅 리소스를 자동으로 관리합니다. 사용자가 생성하는 링크는 NetApp 계정의 일부이며 AWS 계정과 연결됩니다.

링크를 생성한 후에는 하나 또는 여러 개의 FSx for ONTAP 파일 시스템과 연결할 수 있습니다. 각 파일 시스템은 동일한 NetApp 계정 내에서 하나의 링크에만 연결할 수 있습니다. NetApp 계정이 여러 개인 경우, 하나의 파일 시스템을 다른 NetApp 계정의 추가 링크와 연결할 수 있습니다.

Workload Factory의 스토리지 워크로드에서 링크를 생성하고 연결합니다.

Workload Factory 자격 증명 서비스에 저장된 자격 증명 또는 AWS Secrets Manager에 저장된 자격 증명을 사용하여 링크를 인증할 수 있습니다. Workload Factory는 인증 모드 변경을 지원하지 않습니다.

GovCloud 계정에 대한 링크 연결이 지원됩니다. Workload Factory는 GovCloud 인증 키를 사용하여 GovCloud 승인 메커니즘을 통해 FSx for ONTAP 작업에 안전하고 에이전트 없이 액세스할 수 있도록 합니다.



[[costs]]
== 비용

Lambda가 수행하는 모든 트랜잭션에는 요금이 부과됩니다. Lambda는 두 시스템 간의 프록시 역할을 하므로, Lambda가 파일 시스템의 ONTAP REST API에 요청을 보낼 때와 Workload Factory에 응답을 보낼 때 요금이 발생합니다.

link:https://aws.amazon.com/lambda/pricing/["AWS Lambda 사용과 관련된 비용에 대해 자세히 알아보십시오."^]



[[when-a-link-is-required]]
== 링크가 필요한 경우

Workload Factory는 일부 정보를 표시하고 일부 작업을 수행하기 위해 링크가 필요합니다. 링크가 필요한 작업을 수행하려고 하는데 FSx for ONTAP 파일 시스템과 링크를 연결하지 않은 경우 Workload Factory는 해당 작업에 링크가 필요하다는 알림을 표시합니다.

링크가 필요한 기능은 다음과 같습니다.

* 사전 예방적 유지 관리, 안정성 및 비용 대비 성능 최적화를 위한 FSx for ONTAP 파일 시스템 구성의 우수한 아키텍처 상태
* ONTAP EMS 이벤트 모니터링 및 알림
* NetApp 자율형 랜섬웨어 보호(ARP/AI)
* FSx for ONTAP 파일 시스템 전반에 걸쳐 향상된 통합 용량 가시성
* 볼륨 및 스토리지 VM 데이터 복제, 관리 및 모니터링
* SMB/CIFS 공유 및 NFS 엑스포트 정책 프로비저닝 및 관리
* FSx for ONTAP 파일 시스템에서 iSCSI 볼륨 관리
* 사용자 지정 보호 SLA를 위한 스냅샷 정책 생성 및 관리
* 자동 용량 관리를 위한 Inode 관리 기능 향상
* 탄력적 확장을 위한 볼륨 자동 증가
* 즉각적인 인플레이스 데이터 클로닝을 위한 클론 생성 및 관리
* ONTAP 버전 등 ONTAP에서 직접 추가 메트릭 표시
* 스토리지 VM 및 클러스터 LIF의 역할, 엔드포인트, 노드, IP 주소 및 상태를 포함한 세부 정보 표시




[[related-information]]
== 관련 정보

* link:https://docs.netapp.com/us-en/workload-setup-admin/create-link.html["FSx for ONTAP 파일 시스템에 링크 연결"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/manage-links.html["링크 관리"]

