---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory는 워크로드 구성을 스캔하여 안정성, 보안, 운영 우수성, 비용 최적화 및 성능 효율성을 평가하고, 운영 우수성을 달성하는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= 잘 설계된 워크로드를 구축하고 운영합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory는 Amazon FSx for NetApp ONTAP NetApp 관리 제품군으로, AWS Well-Architected Framework에 부합하는 안정적이고 안전하며 효율적이고 비용 효율적인 스토리지 및 데이터베이스 구성을 유지 관리하고 운영할 수 있도록 지원합니다. Workload Factory는 스토리지 및 데이터베이스 워크로드에 대한 일일 분석, 권장 사항 및 자동 수정 기능을 제공하여 워크로드의 정상적인 운영을 지원합니다. Workload Factory는 이 프로세스를 자동화함으로써 인적 오류를 최소화하고 작업량 관리의 일관성을 보장합니다.



== 작동 원리

Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템, Microsoft SQL Server 및 Oracle 데이터베이스 배포를 매일 분석합니다. 이 분석은 잘 설계된 상태, 인사이트 및 권장 사항을 제공합니다. 구성 문제를 자동으로 수정하여 모범 사례를 충족하고 효율적으로 운영할 수 있습니다.

일일 분석이 완료되면 배포에 대한 구성이 Well-architectured 대시보드에 "최적화됨" 또는 "최적화되지 않음"으로 표시됩니다. 여기에서 전체 최적화 점수, 범주별 구성 문제, 구성 문제 목록 및 권장 사항을 확인할 수 있습니다. 구성 문제에 대한 권장 사항을 검토할 수 있습니다. Workload Factory에서 일부 문제는 자동으로 해결할 수 있지만, 다른 문제는 수동 개입이 필요합니다. 이 경우 Workload Factory는 권장 변경 사항을 구현하는 데 도움이 되는 자세한 지침을 제공합니다.

사용 환경에 적용되지 않는 구성에 대한 분석은 제외할 수 있습니다. 이렇게 하면 불필요한 경고와 부정확한 최적화 결과를 방지할 수 있습니다. 특정 구성 분석을 제외하면 Workload Factory는 해당 구성을 전체 최적화 점수 계산에 포함하지 않습니다.



== 왜 중요한가

Workload Factory는 지속적인 평가와 권장 사항 인사이트 및 문제 해결을 결합하여 대규모 스토리지 또는 데이터베이스 환경에 모범 사례를 적용합니다. 자동화된 수정 기능은 인적 오류를 줄이고 일관된 관리를 보장하며 성능과 안정성을 유지합니다. Workload Factory 콘솔에서 적용되는 수정 사항은 인적 오류를 줄이고 일관된 관리를 보장합니다. 자동화를 통해 구성이 정확하게 적용되고 유지 관리되므로 워크로드 인프라 전반에서 성능과 안정성을 유지할 수 있습니다.



== Workload Factory를 사용하여 잘못된 구성을 감지하고 수정해 보세요.

Workload Factory를 시작하려면 가입하고 자격 증명을 추가한 다음 연결을 설정하여 AWS 리소스를 관리하고 Amazon FSx for NetApp ONTAP를 사용하여 워크로드를 최적화하십시오.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["빠른 시작"]



== 스토리지 워크로드에 대한 모범 사례 및 권장 사항

Workload Factory는 스토리지 구성을 평가하여 ONTAP 구성 모범 사례에 대한 심층적인 분석과 AWS Well-Architected Framework 준수 여부를 제공합니다. 또한, 개선 사항 및 수정 사항에 대한 권장 사항도 제시합니다.

잘 설계된 분석은 프레임워크의 다음 핵심 요소인 신뢰성, 보안, 운영 우수성, 비용 최적화 및 성능 효율성으로 구성을 분류합니다.



=== 신뢰할 수 있음

신뢰성은 장애가 발생하더라도 워크로드가 의도된 기능을 정확하고 일관되게 수행하도록 보장합니다.

* * ONTAP 백업을 위해 FSx를 예약하세요*
+
FSx for ONTAP: 볼륨을 백업하면 데이터 보존 및 규정 준수 요구 사항을 지원하는 데 도움이 됩니다. FSx for ONTAP 백업을 사용하여 데이터에 대한 자동 백업 및 보존을 설정하십시오.

* *로컬 스냅샷 예약*
+
효율적인 백업과 빠른 복원을 위해 로컬 스냅샷을 예약하세요. 스냅샷은 볼륨의 특정 시점의 모습을 즉시 보여주는 이미지입니다.

* *지역 간 복제*
+
리전 간 복제는 데이터를 다른 AWS 리전으로 복제하여 데이터의 내구성과 가용성을 향상시킵니다. NetApp Workload Factory는 재해 복구 및 규정 준수를 위해 리전 간 복제 설정을 권장합니다.

* *데이터 복제 설정*
+
데이터 신뢰성을 높이기 위해 데이터를 동일 지역 또는 다른 지역의 FSx for ONTAP 파일 시스템으로 복제할 수 있습니다. 파일 시스템 간 마이그레이션, 재해 복구 및 장기 보존을 지원하기 위해 데이터 복제를 설정하십시오.

* *SSD 용량 임계값 높이기*
+
SSD 스토리지 계층의 사용률은 지속적으로 80%를 초과해서는 안 됩니다. 이는 용량 풀 스토리지 계층의 데이터 읽기 및 쓰기에 영향을 미치고 파일 시스템의 처리량 용량에 영향을 줄 수 있습니다. 용량이 부족해지면 데이터 볼륨이 읽기 전용으로 전환될 수 있으며, 새 데이터를 쓰려는 서비스가 실패할 수 있습니다.

* *데이터 신뢰성을 확보하기 위해 라벨을 일치시키세요.*
+
데이터의 안정성을 보장하려면 소스 볼륨의 스냅샷 정책 레이블과 복제 정책 레이블이 일치해야 합니다.

* *파일 용량 임계값 증가*
+
볼륨 용량 제한에 도달하는 것을 방지하기 위해 파일 용량 임계값을 높여야 합니다. 파일 용량(inode) 부족으로 인해 볼륨에 추가 데이터를 쓸 수 없습니다. Workload Factory는 사용 가능한 파일 용량의 활용률을 지속적으로 80% 미만으로 유지할 것을 권장합니다. 볼륨에 새 파일을 생성하려면 사용 가능한 파일 용량이 필요합니다.





=== 보안

보안은 위험 평가 및 완화 전략을 통해 데이터, 시스템 및 자산을 보호하는 데 중점을 둡니다.

* *ARP/AI 활성화*
+
NetApp AI 기반 자율형 랜섬웨어 보호(ARP/AI)는 랜섬웨어 위협으로부터 볼륨을 보호하는 데 도움을 줍니다. Workload Factory는 모든 볼륨에 대해 ARP/AI를 활성화할 것을 권장합니다.

* *볼륨에 대한 무단 접근*
+
iSCSI를 사용하여 애플리케이션 데이터를 제공하는 볼륨은 NAS에 병렬로 액세스하는 것을 허용해서는 안 됩니다. Workload Factory는 iSCSI 프로토콜을 통해 액세스하는 볼륨에 대해서는 추가 프로토콜 사용을 제한할 것을 권장합니다.





=== 운영 우수성

운영 효율성은 최적의 아키텍처와 비즈니스 가치를 제공하는 데 중점을 둡니다.

* *자동 용량 관리 활성화*
+
SSD 계층이 임계값을 초과하지 않도록 정기적으로 관리하려면 자동 용량 관리를 활성화해야 합니다.

* *용량 활용률 임계값*
+
Workload Factory는 용량 활용률이 지속적으로 80%를 초과하지 않도록 권장합니다. 이는 애플리케이션의 데이터 읽기 및 쓰기에 영향을 미칠 수 있습니다. 용량 증가는 수동 또는 용량 자동 증가 기능을 사용하여 자동으로 수행할 수 있습니다.

* *용량 활용률이 거의 최대치에 도달했습니다*
+
워크로드 팩토리는 용량이 거의 꽉 찼을 때 애플리케이션 중단을 방지하기 위해 용량을 늘리는 조치를 취할 것을 권장합니다.

* *캐시 관계 쓰기 모드*
+
최적의 성능을 위해 Workload Factory는 워크로드에 가장 적합한 캐시 관계 쓰기 모드를 권장합니다. 쓰기 우회 모드는 작은 파일에 대한 읽기 중심 워크로드에서 더 나은 성능을 제공하는 반면, 쓰기 백 모드는 큰 파일에 대한 쓰기 중심 워크로드에서 더 나은 성능을 제공합니다.

* *캐시 볼륨 크기 최적화*
+
Workload Factory는 최적의 크기를 유지하고 캐시가 자주 사용되는 데이터에 집중하여 효율성을 극대화할 수 있도록 캐시 볼륨에서 볼륨 자동 크기 조정 및 스크러빙을 활성화하는 것을 권장합니다.

* *스토리지 VM 논리적 보고*
+
Workload Factory에서는 볼륨 수준에서 스토리지 사용량을 더 잘 파악할 수 있도록 스토리지 VM의 기본 보고 설정을 논리적으로 설정하는 것을 권장합니다.





=== 비용 최적화

비용 최적화는 비용을 낮게 유지하면서 비즈니스에 가장 큰 가치를 얻을 수 있도록 도와줍니다.

* *콜드 데이터를 계층화하여 총소유비용(TCO)을 최적화하세요*
+
SSD 스토리지 계층 사용률을 줄이기 위해 콜드 데이터 계층화를 활성화해야 합니다. 각 볼륨에 계층화 정책을 적용하는 것이 좋습니다. FSx for ONTAP 데이터를 지속적으로 스캔하여 콜드 데이터를 감지하고 중단 없이 용량 스토리지 풀 계층으로 이동합니다.

* *저장 효율성을 향상시키세요*
+
스토리지 활용도를 최적화하고 SSD 계층 비용을 절감하기 위해 압축, 데이터 중복 제거와 같은 스토리지 효율성 향상 기능을 활성화해야 합니다.

* *불필요한 스냅샷 및 백업 삭제*
+
비용 절감을 위해 더 이상 필요하지 않은 스냅샷과 백업은 삭제해야 합니다.

* *분리된 블록 디바이스*
+
블록 디바이스를 7일 동안 사용하지 않으면 Workload Factory에서는 비용 절감을 위해 블록 디바이스 데이터를 아카이빙하거나 사용하지 않는 블록 디바이스를 삭제할 것을 권장합니다.





== 데이터베이스 워크로드에 대한 모범 사례 및 권장 사항

Workload Factory는 잘 설계된 데이터베이스 워크로드를 운영하기 위한 모범 사례 및 권장 사항을 제공합니다. 잘 설계된 아키텍처 분석은 스토리지 크기, 스토리지 레이아웃, 스토리지 구성, 컴퓨팅, 애플리케이션(SQL Server) 및 복원력과 관련된 Microsoft SQL Server 및 Oracle 데이터베이스 구성 및 설정을 평가합니다.



=== 저장 크기

* *저장 계층*
+
최적의 스토리지 성능을 위해 기본 SSD 계층에 FSx for ONTAP 볼륨을 생성하십시오. 용량 풀 계층을 사용하면 성능이 저하되고 지연 시간이 증가할 수 있습니다.

* *파일 시스템 여유 공간*
+
스토리지 성능을 최적화하려면 파일 시스템 용량을 볼륨 전체 크기의 1.35배로 설정하십시오.

+
파일 시스템 여유 공간 비율은 다음과 같습니다.

+
** 공급 부족: 35% 미만
** 최적화 범위: 35-100%
** 과잉 공급: > 100%


* *통나무 드라이브 크기*
+
SQL Server 로그 드라이브의 크기를 정확하게 관리하고 정기적으로 모니터링하여 로그 드라이브 용량 부족으로 인한 트랜잭션 롤백, 데이터베이스 사용 불가, 데이터 손상 및 성능 저하와 같은 문제를 방지하십시오.

+
로그 드라이브 크기 비율은 다음과 같습니다.

+
** 준비 부족: 20% 미만
** 최적화: 20-30%
** 과잉 공급: > 30%


* *TempDB 드라이브 크기*
+
SQL Server TempDB의 크기를 정확하게 설정하고 정기적으로 모니터링하여 성능을 최적화하고 전반적인 안정성을 유지하십시오. TempDB를 올바르게 구성하면 성능 문제와 불안정성을 방지할 수 있습니다. 공간 부족 또는 높은 경합률은 쿼리 속도 저하, 애플리케이션 시간 초과 및 시스템 충돌로 이어질 수 있습니다.

+
TempDB 드라이브 크기 비율은 다음과 같습니다.

+
** 공급 부족: 10% 미만
** 최적화: 10-20%
** 과잉 공급: > 20%






=== 수납 공간 배치

* *데이터 파일(.mdf) 배치*
+
성능 향상, 독립적인 백업 일정 설정 및 복원 기능 개선을 위해 데이터 파일과 로그 파일을 서로 다른 드라이브에 분리하십시오. 소규모 데이터베이스의 경우 데이터 및 로그 LUN 경로를 서로 다른 볼륨으로 분리하십시오. 이러한 분리는 500GiB 이상의 대규모 데이터베이스가 두 개 이상인 경우에 필수적입니다.

* *로그 파일(.ldf) 위치*
+
성능 향상, 독립적인 백업 일정 설정 및 복원 기능 개선을 위해 데이터 파일과 로그 파일을 서로 다른 드라이브에 분리하십시오. 소규모 데이터베이스의 경우 데이터 및 로그 LUN 경로를 서로 다른 볼륨으로 분리하십시오. 이러한 분리는 500GiB 이상의 대규모 데이터베이스가 두 개 이상인 경우에 필수적입니다.

* *TempDB 배치*
+
TempDB를 전용 드라이브에 배치하여 TempDB I/O를 격리하고 다른 데이터베이스와의 I/O 경합을 방지하십시오. 이 최적화는 SQL Server의 전반적인 성능과 안정성을 향상시킵니다. 이를 준수하지 않을 경우 심각한 I/O 병목 현상, 쿼리 성능 저하 및 시스템 불안정성이 발생할 수 있습니다.





=== 스토리지 구성

* * ONTAP 구성 *
+
[cols="1a,1a,2a"]
|===
| 실재 | 환경 | 권장 사항 


 a| 
용량
 a| 
** 씬 프로비저닝(-space-guarantee = none)
** 자동 크기 조정
** 자동 크기 조정 모드 = 성장
** 부분준비금 = 0%
** 스냅샷 사본 예약 = 0%
** 스냅샷 자동 삭제(볼륨/가장 오래된 스냅샷부터)
** 공간 관리 시도 우선 = 볼륨 증가

 a| 
스토리지 효율성과 비용 효율성을 최적화하려면 FSx for ONTAP 볼륨에 대해 씬 프로비저닝, 자동 크기 조정 및 공간 관리 옵션을 구성하십시오. 씬 프로비저닝이 없으면 스토리지가 사전에 할당되어 비효율적인 사용과 과잉 프로비저닝으로 인한 비용 증가를 초래합니다. 정적 할당은 사용하지 않는 용량에 대한 비용을 발생시켜 지출을 증가시키고, 동적 할당이 부족하면 확장성과 유연성이 저하되어 성능에 악영향을 미칩니다. 또한 공간 회수가 없으면 삭제된 데이터가 공간을 차지하여 효율성이 떨어집니다.



 a| 
용량
 a| 
** 계층화 정책 = 스냅샷 전용
** 단계별 최소 냉방일수 = 7

 a| 
최적의 데이터베이스 성능과 비용 효율성을 위해 Workload Factory는 스냅샷만 용량 계층으로 이동할 것을 권장합니다. 이 전략은 비용을 절감하면서 높은 성능을 보장합니다. 특히 7일 이상 된 스냅샷은 티어링하는 것이 좋습니다.



 a| 
LUN
 a| 
OS 유형 = 윈도우 2008
 a| 
ONTAP LUN의 OS 유형 값은 I/O 정렬을 위해 운영 체제 파티셔닝 체계와 일치해야 합니다. 잘못된 구성은 최적이 아닌 성능을 초래할 수 있습니다.



 a| 
LUN
 a| 
공간 예약 가능
 a| 
공간 예약이 활성화되면 ONTAP 디스크 공간 부족으로 인해 해당 LUN에 대한 쓰기 작업이 실패하지 않도록 볼륨에 충분한 공간을 예약합니다.



 a| 
LUN
 a| 
공간 할당 활성화됨
 a| 
이 옵션을 선택하면 FSx for ONTAP 이 볼륨이 가득 차서 쓰기를 허용할 수 없을 때 EC2 호스트에 알림을 보냅니다. 이 설정을 사용하면 EC2 호스트의 SQL Server에서 데이터를 삭제할 때 FSx for ONTAP 자동으로 공간을 회수할 수 있습니다. 이 기능을 비활성화하면 쓰기 오류가 발생할 수 있으며 공간이 비효율적으로 사용될 수 있습니다.

|===
* *윈도우 저장소 구성*
+
[cols="1a,1a,2a"]
|===
| 실재 | 환경 | 권장 사항 


 a| 
Microsoft 다중 경로 I/O(MPIO)
 a| 
** 상태 = 활성화됨
** 정책 = 라운드 로빈
** 세션 수 = 5

 a| 
FSx for ONTAP 에 프로비저닝된 LUN을 사용하는 EC2의 Microsoft SQL Server 데이터베이스에 대해 최적의 가동 시간과 데이터 액세스 일관성을 보장하기 위해 Workload Factory는 멀티패스 I/O(MPIO)를 활성화하고 구성하는 것을 권장합니다. MPIO는 ONTAP 용 FSx에 대한 여러 경로를 제공하여 복원력과 성능을 모두 향상시킵니다. 이 모범 사례는 구성 요소에 오류가 발생하더라도 데이터 액세스를 유지함으로써 잠재적인 데이터 손실이나 시스템 중단을 방지합니다.



 a| 
할당 단위 크기
 a| 
NTFS 할당 단위 크기 = 64K
 a| 
NTFS 할당 단위 크기를 64K로 설정하여 디스크 공간을 더 효율적으로 사용하고, 단편화를 줄이며, 파일 읽기/쓰기 성능을 향상시킵니다. 이를 올바르게 구성하지 않으면 비효율적인 디스크 사용 및 성능 저하가 발생할 수 있습니다.

|===




=== 계산하다

* *컴퓨팅 적정화*
+
SQL Server EC2 인스턴스의 최적 성능과 비용 효율성을 보장하기 위해 워크로드 요구 사항에 따라 인스턴스 크기를 적절하게 조정하는 것이 좋습니다. 현재 인스턴스의 리소스가 부족한 경우 업그레이드를 통해 CPU, 메모리 및 I/O 용량을 향상시킬 수 있습니다. 만약 용량이 과도하게 확보된 경우, 용량을 줄이면 성능을 유지하면서 비용을 절감할 수 있습니다.

* *운영체제 패치*
+
Workload Factory는 보안을 강화하고 SQL Server 데이터베이스를 취약점으로부터 보호하며 시스템 안정성을 향상시키기 위해 최신 패치를 적용할 것을 권장합니다.

* *네트워크 어댑터 설정*
+
Microsoft SQL Server 인스턴스에서 최적의 네트워크 성능을 위해서는 수신 측 스케일링(RSS)을 정확하게 구성하는 것이 필수적입니다. RSS는 네트워크 처리를 여러 프로세서에 분산시켜 병목 현상을 방지하고 시스템 성능을 향상시킵니다. Workload Factory는 다음과 같은 RSS 설정을 권장합니다.

+
** TCP 오프로딩 기능 비활성화: 모든 TCP 오프로딩 기능이 비활성화되어 있는지 확인하십시오.
** 수신 큐 개수: vCPU가 8개보다 크면 8로 설정합니다. vCPU 개수가 8개 이하인 경우, 해당 개수로 설정합니다.
** RSS 프로필: NUMAStatic으로 설정하세요.
** 기본 프로세서 번호: 2로 설정.
+
이러한 설정을 따르면 Microsoft SQL Server 인스턴스의 성능과 안정성이 향상됩니다. 운영 환경에 변경 사항을 적용하기 전에 권장 설정을 테스트하여 성능 향상 여부를 확인하는 것이 좋습니다.







=== 응용 프로그램(SQL Server)

* *특허*
+
SQL Server 라이선스 평가 및 권장 사항은 호스트 수준에서 제공됩니다.

+
최적화되지 않음: Workload Factory에서 사용자의 데이터베이스 인프라가 유료 상용 소프트웨어 라이선스 기능 중 어느 것도 사용하지 않는 것으로 감지되면 해당 라이선스는 "최적화되지 않음"으로 간주됩니다. 최적화되지 않은 라이선스는 불필요한 비용을 초래할 수 있습니다.

+
최적화됨: 상용 소프트웨어 라이선스가 데이터베이스 성능 요구 사항을 충족할 때 해당 라이선스는 "최적화됨"으로 간주됩니다.

* *Microsoft SQL Server 패치*
+
Workload Factory는 보안을 강화하고 SQL Server 데이터베이스를 취약점으로부터 보호하며 시스템 안정성을 향상시키기 위해 최신 패치를 적용할 것을 권장합니다.

* *맥스돕*
+
쿼리 성능을 최적화하려면 최대 병렬 처리 수준(MAXDOP)을 설정하여 병렬 처리의 균형을 맞추십시오. 정확한 MAXDOP 설정은 성능과 효율성을 향상시킵니다. MAXDOP 값을 4, 8 또는 16으로 설정하면 대부분의 사용 사례에서 최상의 결과를 얻을 수 있습니다. 워크로드를 테스트하고 CXPACKET과 같은 병렬 처리 관련 대기 유형을 모니터링하는 것이 좋습니다.





=== 신뢰할 수 있음

* * ONTAP 백업을 위해 FSx를 예약하세요*
+
Microsoft SQL Server 볼륨 백업은 데이터 보존 및 규정 준수 요구 사항을 충족하는 데 매우 중요합니다. FSx for ONTAP 백업을 사용하여 SQL Server 데이터에 대한 자동 백업 및 보존을 설정하십시오.

* *로컬 스냅샷 예약*
+
효율적인 백업과 빠른 복원을 위해 로컬 스냅샷을 예약하세요. 스냅샷은 볼륨의 특정 시점의 모습을 즉시 보여주는 이미지입니다.

* *지역 간 복제*
+
리전 간 복제는 데이터를 다른 AWS 리전으로 복제하여 데이터의 내구성과 가용성을 향상시킵니다. NetApp Workload Factory는 재해 복구 및 규정 준수를 위해 리전 간 복제 설정을 권장합니다.





== EVS 워크로드에 대한 모범 사례 및 권장 사항

Workload Factory는 잘 설계된 Amazon Elastic VMware Service(EVS) 워크로드 운영을 위한 모범 사례 및 권장 사항을 제공합니다. 잘 설계된 분석은 EVS 구성을 평가하여 VMware 환경이 안정성, 보안, 운영 우수성, 비용 최적화 및 성능 효율성 측면에서 최적화되도록 지원합니다. VMware의 잘 설계된 상태 탭에서 EVS 환경에 대한 잘 설계된 모범 사례를 구현하는 데 도움이 되는 인사이트와 권장 사항을 확인할 수 있습니다.

잘 설계된 분석은 프레임워크의 다음 핵심 요소인 _신뢰성_ 및 _보안_을 기준으로 구성을 분류합니다.



=== 신뢰할 수 있음

신뢰성은 장애가 발생하더라도 워크로드가 의도된 기능을 정확하고 일관되게 수행하도록 보장합니다.

* *EVS 환경 복원력*
+
EVS 클러스터 노드가 파티션 배치 그룹에 올바르게 분산되어 있는지 확인하십시오. 모든 노드는 4개 이상의 파티션으로 구성된 단일 파티션 배치 그룹의 구성원이어야 합니다. 올바른 파티션 배치는 AWS 가용 영역 내의 여러 장애 격리 하드웨어 파티션에 EVS 클러스터 노드가 분산되도록 보장합니다. 잘못 배치되면 파티션 장애 발생 시 처리 능력 손실이나 다운타임이 크게 발생할 수 있습니다.





=== 보안

보안은 위험 평가 및 완화 전략을 통해 데이터, 시스템 및 자산을 보호하는 데 중점을 둡니다.

* *클러스터 노드 관리*
+
EVS 클러스터 노드에 적절한 EC2 중지 및 종료 보호 기능이 구성되어 있는지 확인하십시오. EVS ESXi 노드는 vCenter 또는 기타 VMware 수준의 관리 도구를 사용하여 관리해야 합니다. 적절한 EC2 수준 보호 기능이 없으면 EC2 콘솔에서 노드가 실수로 중지되거나 종료될 수 있으며, 이로 인해 가상 머신 데이터의 사용 불가 또는 데이터 손실이 발생할 수 있습니다.





== 관련 정보

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ONTAP 파일 시스템을 위한 잘 설계된 FSx를 구현합니다."^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["잘 설계된 데이터베이스 워크로드를 구현하세요"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["잘 설계된 EVS 구성 구현"^]

