---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory는 워크로드 구성을 스캔하여 안정성, 보안, 운영 우수성, 비용 최적화 및 성능 효율성을 평가하고, 운영 우수성을 달성하는 데 도움이 되는 통찰력과 권장 사항을 제공합니다. 
---
= NetApp Workload Factory를 사용하여 아키텍처가 잘 설계된 워크로드를 구축하고 운영하세요
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory는 Amazon FSx for NetApp ONTAP용 NetApp 관리 제품군으로, AWS Well-Architected Framework에 부합하는 안정적이고 안전하며 효율적이고 비용 효율적인 워크로드 구성을 유지 및 운영할 수 있도록 지원합니다. Workload Factory는 워크로드에 대한 일일 분석, 권장 사항 및 자동 수정 기능을 제공하여 정상적인 워크로드 운영을 촉진합니다. 이러한 프로세스를 자동화함으로써 Workload Factory는 인적 오류를 최소화하고 워크로드 관리의 일관성을 보장합니다.



== 작동 원리

Workload Factory는 Amazon FSx for NetApp ONTAP 파일 시스템 배포 환경에서 실행되는 워크로드를 매일 분석합니다. 이 분석을 통해 아키텍처 상태, 인사이트 및 권장 사항을 확인할 수 있습니다.

일일 분석이 완료되면 배포에 대한 구성이 Well-architectured 대시보드에 "최적화됨" 또는 "최적화되지 않음"으로 표시됩니다. 여기에서 전체 최적화 점수, 범주별 구성 문제, 구성 문제 목록 및 권장 사항을 확인할 수 있습니다. 구성 문제에 대한 권장 사항을 검토할 수 있습니다. Workload Factory에서 일부 문제는 자동으로 해결할 수 있지만, 다른 문제는 수동 개입이 필요합니다. 이 경우 Workload Factory는 권장 변경 사항을 구현하는 데 도움이 되는 자세한 지침을 제공합니다.

사용 환경에 적용되지 않는 구성에 대한 분석은 제외할 수 있습니다. 이렇게 하면 불필요한 경고와 부정확한 최적화 결과를 방지할 수 있습니다. 특정 구성 분석을 제외하면 Workload Factory는 해당 구성을 전체 최적화 점수 계산에 포함하지 않습니다.



== 왜 중요한가

Workload Factory는 지속적인 평가와 권장 사항 인사이트 및 문제 해결을 결합하여 대규모 스토리지, 데이터베이스 및 VMware 환경에 모범 사례를 적용합니다. Workload Factory 콘솔에서 적용되는 자동화된 수정 사항은 인적 오류를 줄이고 일관된 관리를 보장하며 워크로드 인프라 전반의 성능과 안정성을 유지합니다.



== Workload Factory를 사용하여 워크로드 구성 오류를 감지하고 수정해 보세요

Workload Factory를 시작하려면 가입하고 자격 증명을 추가한 다음 연결을 설정하여 AWS 리소스를 관리하고 Amazon FSx for NetApp ONTAP를 사용하여 워크로드를 최적화하십시오.

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["빠른 시작"]



== 관련 정보

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ONTAP 파일 시스템을 위한 잘 설계된 FSx를 구현합니다."^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["잘 설계된 데이터베이스 워크로드를 구현하세요"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["잘 설계된 EVS 구성 구현"^]

